"use client"
import Header from "@/components/Common/Header/Header";
import "./globals.css";
import Footer from "@/components/Common/Footer/Footer";



// export const metadata = {
//   title: "Home || Inventory",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
         <> 
         <Header/>
        <div>{children}</div>
        <Footer/>
        </>

      </body>
    </html>
  );
}
