"use client"
import Header from "@/components/Common/Header/Header";
import "./globals.css";
import Footer from "@/components/Common/Footer/Footer";
import { PartnerProvider } from "@/components/PartnerProvider";



// export const metadata = {
//   title: "Home || Inventory",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
         <> 
        <PartnerProvider>
        <Header/>
        <div className="min-h-screen">
          {children}
        </div>
        <Footer/>
        </PartnerProvider>
        </>

      </body>
    </html>
  );
}
